import os
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def add_styled_heading(doc, text, level):
    heading = doc.add_heading(text, level=level)
    run = heading.runs[0]
    run.font.color.rgb = RGBColor(0, 102, 204)  # Professional Blue

def create_tech_doc(language):
    # Initialize using the provided template if available
    template_path = 'templateprvs.docx'
    if os.path.exists(template_path):
        doc = Document(template_path)
    else:
        print(f"Warning: {template_path} not found. Using default document.")
        doc = Document()
    
    content = {
        'it': {
            'filename': 'Parvis Loggy-Eye_Technical_Presentation_IT.docx',
            'title': 'Parvis Loggy-Eye: Relazione Tecnica Integrata',
            'subtitle': 'Suite Diagnostica per l\'Ecosistema Abaco Server',
            'sections': [
                {
                    'heading': '1. Introduzione ed Executive Summary',
                    'content': 'Parvis Loggy-Eye è una suite diagnostica avanzata progettata per supportare i reparti tecnici nella manutenzione e analisi dei log generati dai sistemi Abaco. Lo strumento trasforma dati grezzi voluminosi in intelligence azionabile attraverso una UI professionale, riducendo drasticamente il MTTR (Mean Time To Repair).'
                },
                {
                    'heading': '2. Architettura e Performance del Sistema',
                    'content': 'L\'applicazione combina tecnologie moderne per garantire fluidità forense anche con file di grandi dimensioni:',
                    'list': [
                        'Stack Tecnologico: Basato su Electron e React.js per un deployment standalone (Zero-Zero Config).',
                        'Rendering Virtualizzato: Gestione di log >100MB tramite virtual scrolling (solo le righe visibili sono renderizzate nel DOM).',
                        'Parsing Asincrono: Motore di estrazione metadati basato su regex ottimizzate per evitare il blocco del thread principale.'
                    ]
                },
                {
                    'heading': '3. Motore di Analisi Forense e Boot Tracking',
                    'content': 'Parvis Loggy-Eye non è un semplice visualizzatore, ma un motore analitico bidirezionale:',
                    'list': [
                        'Sincronizzazione Dashboard-Log: Ogni evento rilevato (erogazione, errori, warning) permette il jump immediato alla riga esatta del file grezzo.',
                        'Algoritmo Boot Anomaly: Rilevamento automatico di startup sequenziali o blackout, con riepilogo in prosa professionale.',
                        'Supporto Multimodale: Gestione unificata di ICS Log e Server Library Log con estrazione automatica da rete (MDR).'
                    ]
                },
                {
                    'heading': '4. Valore Aziendale e Impatto sul Service',
                    'content': 'Lo strumento impatta positivamente su diversi stakeholder:',
                    'list': [
                        'Field Support: Diagnostica autonoma on-site senza dipendenza diretta dal team di sviluppo.',
                        'Relazione con il Cliente: Fornitura di report tecnico-professionali invece di stringhe di log oscure.',
                        'Efficienza QA: Validazione rapida dei flussi di produzione durante i test di collaudo.'
                    ]
                },
                {
                    'heading': '5. Conclusione',
                    'content': 'Parvis Loggy-Eye rappresenta lo standard di riferimento per la diagnostica tecnica dei server Abaco, integrando potenza di calcolo e semplicità visuale in un unico pacchetto portabile.'
                }
            ],
            'footer': '© 2026 Progetto Parvis Loggy-Eye — Proprietà Riservata.'
        },
        'en': {
            'filename': 'Parvis Loggy-Eye_Technical_Presentation_EN.docx',
            'title': 'Parvis Loggy-Eye: Integrated Technical Report',
            'subtitle': 'Diagnostic Suite for the Abaco Server Ecosystem',
            'sections': [
                {
                    'heading': '1. Introduction and Executive Summary',
                    'content': 'Parvis Loggy-Eye is an advanced diagnostic suite designed to support technical departments in the maintenance and analysis of logs generated by Abaco systems. The tool transforms voluminous raw data into actionable intelligence through a professional UI, drastically reducing MTTR (Mean Time To Repair).'
                },
                {
                    'heading': '2. Architecture and System Performance',
                    'content': 'The application combines modern technologies to ensure forensic fluidity even with large files:',
                    'list': [
                        'Tech Stack: Based on Electron and React.js for standalone deployment (Zero-Zero Config).',
                        'Virtualized Rendering: Handling of >100MB logs via virtual scrolling (only visible rows are rendered in the DOM).',
                        'Asynchronous Parsing: Metadata extraction engine based on optimized regex to avoid main thread lockups.'
                    ]
                },
                {
                    'heading': '3. Forensic Analysis Engine and Boot Tracking',
                    'content': 'Parvis Loggy-Eye is not just a text viewer, but a bidirectional analytical engine:',
                    'list': [
                        'Dashboard-Log Sync: Every detected event (production, errors, warnings) allows for an immediate jump to the exact line in the raw file.',
                        'Boot Anomaly Algorithm: Automatic detection of sequential startups or blackouts, with professional prose summaries.',
                        'Multimodal Support: Unified management of ICS Logs and Server Library Logs with automatic network extraction (MDR).'
                    ]
                },
                {
                    'heading': '4. Business Value and Service Impact',
                    'content': 'The tool positively impacts various stakeholders:',
                    'list': [
                        'Field Support: Autonomous on-site diagnostics without direct dependency on the development team.',
                        'Client Relations: Provision of professional technical reports instead of obscure log strings.',
                        'QA Efficiency: Rapid validation of production flows during factory acceptance tests.'
                    ]
                },
                {
                    'heading': '5. Conclusion',
                    'content': 'Parvis Loggy-Eye represents the reference standard for technical diagnostics of Abaco servers, integrating computing power and visual simplicity in a single portable package.'
                }
            ],
            'footer': '© 2026 Parvis Loggy-Eye Project — Confidential Property.'
        }
    }
    
    data = content[language]
    
    # Title
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(data['title'])
    run.font.size = Pt(28)
    run.font.bold = True
    run.font.color.rgb = RGBColor(0, 51, 102)
    
    # Subtitle
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(data['subtitle'])
    run.font.size = Pt(16)
    run.font.italic = True
    run.font.color.rgb = RGBColor(102, 102, 102)
    
    doc.add_paragraph('\n')
    
    # Sections
    for section in data['sections']:
        add_styled_heading(doc, section['heading'], level=1)
        p = doc.add_paragraph(section['content'])
        p.paragraph_format.space_after = Pt(6)
        
        if 'list' in section:
            for item in section['list']:
                try:
                    doc.add_paragraph(item, style='List Bullet')
                except:
                    # Fallback for templates without 'List Bullet' style
                    doc.add_paragraph(f"• {item}")
                
        doc.add_paragraph('\n')
        
    doc.save(data['filename'])
    print(f"Generated {data['filename']}")

if __name__ == "__main__":
    create_tech_doc('it')
    create_tech_doc('en')
